# This is a basic workflow to help you get started with Actions

name: Build SASS and Deploy to 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Sass Build
        uses: gha-utilities/sass-build@v0.4.8
        with:
          # Relative path(s) to SASS or SCSS file, eg. _scss/main.scss
          source: '**.scss'
          # Path(s) compiled CSS should be saved, eg. ~/workspace_sass/assets/css/main.css
          destination: '**.css'
          # May be boolean or string, see https://sass-lang.com/documentation/js-api#sourcemap
          sourceMap: false
          
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          keep_history: true
